### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Reual4412** [ItsDeidara/DNSwitch4All#1]
I can't seem to get the 3.6 .py to work my os is windows 10. and here what it says when ran with python in cmd. Traceback (most recent call last):
  File "C:\Users\crazy\Desktop\DNSwitch4All 3.6.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests' I do have it setup where my path is setup for python. And answer to what I did wrong.

**Comment by StonedModder** [comment]
This isn't an issue. Please use the release thread for support. https://www.se7ensins.com/forums/threads/release-dnswitch-a-utility-to-hijack-the-webbrowser.1625475/
